### ISSUE TITLE
TriOS "Update" button on toast remains greyed-out and unclickable after downloading an update

### ISSUE THREAD

**Issue by nissa-seru** [wispborne/TriOS#51] opened 2024-07-23 16:07 UTC
Minor bug, flagging in case helpful. 
![Screenshot 2024-07-23 120651](https://github.com/user-attachments/assets/ae3294d1-e966-49b7-ad2d-cd6082d4f646)

[latest.log](https://github.com/user-attachments/files/16351574/latest.log)

**Comment by wispborne** [comment] 2024-07-23 18:55
> Read config from File: 'C:\WINDOWS\system32\cache\TriOS-VersionCheckerCache.json': 0 entries.

Somehow, the `Directory.current` variable is getting set to system32. It's been happening to quite a few people. No idea why yet.

**Comment by nissa-seru** [comment] 2024-07-23 21:21
Hmm, that feels related to TriOS being run as admin.

**Comment by nissa-seru** [comment] 2024-07-25 03:13
Another data point in case helpful; I ran into the same issue again a few
minutes ago (on TriOS v0.1.3) when I tried to use the "Add mod" feature.
Restarted TriOS, did not resolve. However, while digging, I noticed that
TriOS had created "cache" and "logs" folders in the Start Menu folder
containing the shortcut that I usually use to run TriOS - this prompted a
bit of deja vu, since it'd happened to me before when running a script from
a shortcut previously; in that instance, the directory containing the
shortcut was being considered by my script as the current directory. Sure
enough, directly running TriOS from the folder where I had previously
extracted it (without using the shortcut) resolved the issue. Wondering if
a chdir/context manager or similar is just needed to set the working
directory to the location of the TriOS executable.

**Comment by wispborne** [comment] 2024-07-25 03:44
Hah. 18ae9f6ffc0a8fb5b8237934c9daa45a81310250

> Wondering if
a chdir/context manager or similar is just needed to set the working
directory to the location of the TriOS executable.
That's exactly what I decided to do. I was never able to reproduce this bug, even after making a shortcut and launching from there, but I'm hopefully this will fix it.

**Comment by wispborne** [comment] 2024-07-25 03:52
[TriOS-0.1.4.zip](https://github.com/user-attachments/files/16370186/TriOS-0.1.4.zip)

If the issue is still happening, does this fix it? You can overwrite the existing install.

**Comment by wispborne** [comment] 2024-07-25 06:36
Hopefully fixed in 18ae9f6ffc0a8fb5b8237934c9daa45a81310250

**Closed by wispborne** 2024-07-25 06:36 UTC
Labels: bug, major

**Comment by nissa-seru** [comment] 2024-07-25 12:35
Cool, thanks for the speedy fix. With 0.1.4, I'm seeing logs/cache folders
being created in the correct place (location of the exe, not the shortcut),
and I can no longer repro the system32 issue, so lgtm!
