### ISSUE TITLE
Feature Request: Show visual indicator within TriOS when game is loading after being launched through TriOS

### ISSUE THREAD

**Issue by nissa-seru** [wispborne/TriOS#102] opened 2024-09-29 16:29 UTC
Given the game's long load times with mods, would be helpful from UX perspective and also to reduce likelihood of user pushing start button multiple times for various reasons (impatience, uncertainty whether it is launching or something went wrong, etc.)

**Comment by wispborne** [comment] 2024-10-30 14:59
Duplicate of #16

**Closed by wispborne** 2024-10-30 14:59 UTC
